import "@/styles/globals.css";
import { Montserrat } from "next/font/google";
import { ToastProvider, useToast } from "@/components/hooks/useToast";
import Header from "@/components/component/Header/Header";
import ThemeSwitcher from "@/components/component/Header/ThemeSwitcher";
import ThemeProvide from "@/components/component/Header/ThemeProvide";
import Head from "next/head";
import "@/styles/globals.css";
import Layout from "@/components/component/Layout/Layout";
import Footer from "@/components/component/Footer/Footer";
import { BackgroundBeamsWithCollisionDemo } from "@/components/component/Footer/BackgroundBeamsWithCollisionDemo";
import { CountryProvider } from "@/components/context/CountryContext";
import { Provider } from "react-redux";
import store from "@/store/store";
import { useRouter } from "next/router";
import HotelHeader from "./Hotels/components/Header/HotelHeader";
import { HotelCityProvider } from "@/components/context/HotelCityContext";
import { HotelDetailsIdProvider } from "@/components/context/HotelDetailsId";

export const metadata = {
  title: "MakeMyTrip App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export default function App({ Component, pageProps }) {
  const router = useRouter();
  let header;
  switch (router.pathname) {
    case "/":
      header = <Header />;
      break;
    case "/Hotels":
      header = <HotelHeader />;
    case "/Hotels/HotelDetails/[id]":
      header = <HotelHeader />;
      break;
    default:
      header = <Header />;
  }

  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={`${montserrat.variable} font-mont w-full min-h-screen`}>
        <ToastProvider>
          <ThemeProvide>
            <Provider store={store}>
              <CountryProvider>
                <HotelDetailsIdProvider>
                  <HotelCityProvider>
                    {header}
                    <ThemeSwitcher />
                    <Component {...pageProps} />
                    <BackgroundBeamsWithCollisionDemo />
                  </HotelCityProvider>
                </HotelDetailsIdProvider>
              </CountryProvider>
            </Provider>
          </ThemeProvide>
        </ToastProvider>
      </main>
    </>
  );
}
