import '@/styles/globals.css'
import { Montserrat } from 'next/font/google';
import { ToastProvider, useToast } from '@/components/hooks/useToast';
import Header from '@/components/component/Header/Header';
import ThemeSwitcher from '@/components/component/Header/ThemeSwitcher';
import ThemeProvide from "@/components/component/Header/ThemeProvide"
import Head from "next/head";
import '@/styles/globals.css'; 
import Layout from '@/components/component/Layout/Layout';

export const metadata = {
  title: 'MakeMyTrip App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main
        className={`${montserrat.variable} font-mont w-full min-h-screen`}
      >
        <ToastProvider>
          <ThemeProvide>
            <Header />
            <ThemeSwitcher />
            <Component {...pageProps} />
          </ThemeProvide>
        </ToastProvider>
      </main>
    </>
  )
}
