// pages/index.js
import Head from 'next/head';
import { Montserrat } from 'next/font/google'; // Import Montserrat font
import styles from '@/styles/Home.module.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont', // Custom CSS variable for the font
});

export default function Home() {
  return (
    <>
      <Head>
        <title>MakeMyTrip App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${montserrat.variable}`}>
        <div>
          <h1 className='text-dark'>Next.js</h1>
        </div>
      </main>
    </>
  );
}
